auth:
  rootPassword: "RootPass123!"
  database: wordpress
  username: user
  password: "DbPass123!"

primary:
  persistence:
    enabled: true

service:
  type: ClusterIP
  port: 3306

metrics:
  enabled: false

architecture: standalone

# Optionnel : garder un comportement cohérent avec l’ancien projet
# mais le chart standard n’utilise pas les clefs Galera.
