externalDatabase:
  host: mariadb-release.default.svc.cluster.local
  port: 3306
  user: user
  password: "DbPass123!"
  database: wordpress

wordpressDatabaseHost: mariadb-release.default.svc.cluster.local
wordpressDatabaseName: wordpress
wordpressDatabaseUser: user
wordpressDatabasePassword: "DbPass123!"
wordpressUsername: admin
wordpressPassword: "WpPass123!"
persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    memory: 512Mi
    cpu: 300m
  limits:
    memory: 1Gi
    cpu: 600m
mariadb:
  enabled: false

# wordpressPlugins:
#   - name: azure-storage
#     active: true

# azureBlobStorage:
#   accountName: REPLACE_WITH_STORAGE_ACCOUNT_NAME
#   accountKey: REPLACE_WITH_STORAGE_ACCOUNT_KEY
#   containerName: wordpress
