apiVersion: v1
kind: Secret
metadata:
  name: mariadb-credentials
  namespace: default
type: Opaque
stringData:
  mariadb-root-password: "<DB_ROOT_PASSWORD>"
  mariadb-password: "<DB_PASSWORD>"
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-credentials
  namespace: default
type: Opaque
stringData:
  wordpress-password: "<WORDPRESS_PASSWORD>"
  mariadb-password: "<DB_PASSWORD>"